---
title: "Seurat_practice"
output: rmarkdown::github_document
date: "2025-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages 
```{r} 
library(dplyr)
library(Seurat)
library(patchwork)
```

Load data 
```{r}
# Load the PBMC dataset
pbmc.data <- 
  Read10X(data.dir = "data/filtered_gene_bc_matrices/hg19/")

# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- 
  CreateSeuratObject(counts = pbmc.data,
                     project = "pbmc3k",
                     min.cells = 3,
                     min.features = 200)
pbmc




```

Looking at the count matrix
```{r}
pbmc.data[c("CD3D", "TCL1A", "MS4A1"), 1:30]

```

Check size of object
```{r}
dense.size <- object.size(as.matrix(pbmc.data))
dense.size

```

```{r}
sparse.size <- object.size(pbmc.data)
sparse.size
```

```{r}
dense.size/sparse.size
```

# Quaility Control

```{r}
# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
```

Visualise QC using vioine plots
```{r}
# Visualize QC metrics as a violin plot
VlnPlot(pbmc,
        features = c("nFeature_RNA",
                     "nCount_RNA",
                     "percent.mt"),
        ncol = 3)

```

```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

```

```{r}
pbmc <- subset(pbmc,
               subset = nFeature_RNA > 200 & 
                 nFeature_RNA < 2500 & 
                 percent.mt < 5)
```

# Normalising Data

```{r}
pbmc <- NormalizeData(pbmc,
                      normalization.method = "LogNormalize",
                      scale.factor = 10000)
```

```{r}
pbmc <- NormalizeData(pbmc)

```

# feature selection

```{r}
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```

